// 12. Analisa
// Saat tampil("ali") dijalankan, program mencetak "OK!". Namun saat tampil("amir") dijalankan, 
// kondisi memicu throw new MyException("amir"), menghentikan aliran normal, 
// dan berpindah ke blok catch pada method main.


class MyException extends Exception {
    private String Teks;
    MyException(String s) {
        Teks = "Exception generated by: " + s;
    }
    @Override
    public String toString() {
        return Teks;
    }
}

class Eksepsi {
    static void tampil(String s) throws MyException {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) {
        try {
            tampil("ali");
            tampil("amir");
        } catch (MyException ex) {
            System.out.println("Tangkap: " + ex);
        }
    }
}